<?php
if(!$this->getConfig('enabled')) return;
//$_productCollection=$this->getProductCollection();

$_helper = $this->helper('catalog/output');
$helpLabels = $this->helper('themevast/labels');
$_featureImgUrl = Mage::getBaseUrl();
?>
<style>
    /*feature title*/
    .featuredproduct .featured-title{border-bottom: 2px solid #fc6426;}
    .featuredproduct .bx-title .feature_title{
        max-width: 900px;
        height: 50px;
        margin: 0 auto;
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-direction: row;
        -webkit-box-orient: horizontal;
        -webkit-box-direction: normal;
        flex-direction: row;
        -ms-flex-pack: justify;
        -webkit-box-pack: justify;
        justify-content: space-between;
        -ms-flex-align: center;
        -webkit-box-align: center;
        align-items: center;}
    .featuredproduct .bx-title .feature_title li{
        float: left;
        width: 300px;
        height: 50px;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
        font-size: 18px;
        color: #010101;
        text-align: center;
        line-height: 50px;
        -webkit-transition: all .2s linear;
        transition: all .2s linear;
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-direction: row;
        -webkit-box-orient: horizontal;
        -webkit-box-direction: normal;
        flex-direction: row;
        -ms-flex-pack: center;
        -webkit-box-pack: center;
        justify-content: center;
        -ms-flex-align: center;
        -webkit-box-align: center;
        align-items: center;cursor: pointer;}
    .featuredproduct .bx-title .feature_title li:hover{color: #ffffff;background-color: #fc6426;}
    .featuredproduct .bx-title .feature_title li.active{color: #ffffff;background-color: #fc6426;cursor: default;}
    /*featureBox*/
    .featuredproduct .featured_out{}
    .featuredproduct .featuredBox{display: none;}
    .featuredproduct .featuredBox.active{display: block;
        width: 90%;
        margin: 0 auto;}
    /*.featuredproduct .featuredBox{opacity:0;position: absolute;z-index: -1;left:15px;top:67px;max-width: 1170px;}
    .featuredproduct .featuredBox.active{display: block;opacity: 1;z-index: 1;}*/
    /*btn*/
    .featuredproduct .bx-wrapper .bx-controls-direction a{top:50%;margin: 0;}
    .featuredproduct .bx-wrapper .bx-controls-direction a.bx-prev{left:0;}
    .div-tabs>a{display: none;}
    .div-tabs>a.active{display: block;}
    .ul-tabs > li{position: relative;display: block;height: 196px;border-bottom: 1px solid #dfdfdf;}
    .ul-tabs > li > a{padding:13px;}
    .ul-tabs > li:last-child {border-bottom: 0;}
    .ul-tabs > li.active > a:before {background-color: #fff;top: 50%;content: "";display: block;height: 10px;left: -5px;margin: 0;position: absolute;right: 0;transform: rotate(-45deg);-moz-transform: rotate(-45deg);-webkit-transform: rotate(-45deg);-o-transform: rotate(-45deg);width: 10px;}
    .img-responsive {display: block;height: auto;max-width: 100%;}

    /*#info-strip*/
    #info-strip .innerContainer>ul{
        max-width: 900px;
        margin: 0 auto;
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-direction: row;
        -webkit-box-orient: horizontal;
        -webkit-box-direction: normal;
        flex-direction: row;
        -ms-flex-pack: justify;
        -webkit-box-pack: justify;
        justify-content: space-between;
        -ms-flex-align: center;
        -webkit-box-align: center;
        align-items: center;
    }
    #info-strip .innerContainer ul li {
        display: inline-block;
        float: left;
        width: 300px;
        height: 72px;
    }
    #info-strip .innerContainer ul li:hover {
        background: #f3f3f3
    }
    #info-strip .innerContainer ul li a {
        display: block;
        position: relative;
        width: 100%;
        height: 100%;
        padding: 15px;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
        text-align: left;
        color: #343434;
        background: url("../skin/frontend/tv_bigboom_package/tv_bigboom1/images/icon-next.png") right 10px center no-repeat;
    }
    #info-strip .innerContainer ul li a:hover{
        text-decoration: none;
    }
    #info-strip .innerContainer ul li a>img {
        float: left;
        margin-right: 10px;
        vertical-align: top;
    }
    #info-strip .innerContainer ul li a>h3 {
        position: relative;
        font-size: 20px;
        font-weight: 700;
        margin: 0;
    }
    #info-strip .innerContainer ul li a>span {
        position: relative;
        font-size: 12px;
        font-weight: 600;
        font-family: 'Open Sans Condensed', sans-serif;
    }
    @media only screen and (max-width: 800px) {
        #info-strip .innerContainer ul {
            width: auto;
            -ms-flex-direction: column;
            -webkit-box-orient: vertical;
            -webkit-box-direction: normal;
            flex-direction: column;
        }
        #info-strip .innerContainer ul li {
            display: inline;
            margin: 0 auto;
            float: none;
            width: 100%;
        }
    }
    .featuredBox .products-grid li.item .price-box{right:6px;}
    .underInfo{
        margin: 10px 0;
        height:80px;
        background: url(../skin/frontend/tv_bigboom_package/tv_bigboom1/images/underInfoStrip.jpg) center center no-repeat;
    }
</style>
<div class="container" id="info-strip">
    <div class="innerContainer">
        <ul class="clear_fix">
            <li> <a href="javascript:void(0)"> <img src="<?php echo $_featureImgUrl.'\skin\frontend\tv_bigboom_package\tv_bigboom1\images\shipping.png'?>" alt="shipping" width="64"><h3>Fri frakt</h3> <span>Skickas nästa arbetsdag</span> </a></li>
            <li> <a href="javascript:void(0)"> <img src="<?php echo $_featureImgUrl.'\skin\frontend\tv_bigboom_package\tv_bigboom1\images\fardigt.png'?>" alt="fardigt" width="45"><h3>Färdigt på15 min</h3> <span>påde flesta reparationer</span> </a></li>
            <li> <a href="javascript:void(0)"> <img src="<?php echo $_featureImgUrl.'\skin\frontend\tv_bigboom_package\tv_bigboom1\images\spara.png'?>" alt="spara" width="34"><h3>Spara 50% - 75%</h3> <span>påflera reparationer påsamma enhet</span> </a></li>
        </ul>
    </div>
</div>
<div class="underInfo">
</div>
<div class="featuredproduct">
	<?php
    /*echo $this->getConfig('title') ? '<div class="bx-title featured-title clearfix">
        <h2 class="f-left" style="display: inline-block;">' .$this->getConfig('title'). '</h2>
        <!--add by jerry-->
        <ul class="f-right">
            <li class="active">Best Selling</li>
            <li>New Arrival</li>
            <li>Featured Product</li>
        </ul>
    </div>' : '';
    */
	?>
    <div class="bx-title featured-title">
        <!--add by jerry-->
        <ul class="feature_title clearfix">
            <li class="active">Populart</li>
            <li>Nytt</li>
            <li>Rea</li>
        </ul>
    </div>

    <div class="featured_out">
	<?php
		// getConfig
		$widthImage  	= $this->getConfig('widthImage') ? $this->getConfig('widthImage') : 135;
		$heightImage 	= $this->getConfig('heightImage') ? $this->getConfig('heightImage') : 135;
		$price   		= $this->getConfig('price');
		$cart    		= $this->getConfig('cart');
		$compare  		= $this->getConfig('compare');
		$wishlist  		= $this->getConfig('wishlist');
		$review  		= $this->getConfig('review');
		$slide  		= $this->getConfig('slide');
		$rows 			= $this->getConfig('rows');
		$class 			= ($slide && $rows > 1) ? '.slide-multirows' : '.products-grid';
	?>
	<?php if ($slide && $rows > 1): ?>
	<div class="slide-multirows">
	<?php endif ?>
    <?php
        //edit by mivec
        $_categoresId = array(29 , 24 , 146);

        $_status = "";
        $_count=1;
        foreach ($_categoresId as $_categoryId) :
            $_category = Mage::getModel("catalog/category")->load($_categoryId);

            $_productCollection = Mage::getModel("catalog/product")
                ->getCollection()
                ->addCategoryFilter($_category)
                ->setPageSize(8)
                ->setOrder("entity_id" , "DESC");
            //echo $_count . "</p>";
            if ($_count==1) {
                $_status = "active";
            } else {
                $_status = "";
            }
        ?>
    <div id="category-<?php echo $_categoryId;?>" class="featuredBox <?php echo $_status?>">
	<?php $_collectionSize = $_productCollection->count() ?>
	<?php $_columnCount = $this->getColumnCount(); ?>
	<?php $j=0; $time = $this->getConfig('playDelay'); ?>
	<?php $i=0; foreach ($_productCollection as $_product): ?>
	<?php $t = $j*$time; $t .='ms'; $j++; ?>
	<?php if ($i++%$_columnCount==0): ?>
	<ul class="products-grid">
	<?php endif ?>
		<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> item-animate">
		<div class="item-inner">
			<?php // Product Image ?>
			<div class="box-images">
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
			<?php $imagehv = $_product->load('media_gallery')->getMediaGalleryImages()->getItemByColumnValue('position','2');
				if($imagehv) : 
				$imagehv = $imagehv->getFile();
				?>
				<img class="img-face-back" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $imagehv)->resize($widthImage, $heightImage) ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			<?php endif ?>
				<img class="img-face" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($widthImage, $heightImage); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			</a>
			</div>
			<div class="product-shop">
				<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
				<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
				<?php if($review): ?>
					<?php echo $this->getReviewsSummaryHtml($_product) ?>
				<?php endif; ?>
				<?php if($price): ?>
					<?php echo $this->getPriceHtml($_product, true) ?>
				<?php endif; ?>
				<div class="actions">
                    <div class="stock_box">
                        <span class="text">Lager</span>
                        <span class="quality"
                              data-quality="
                              <?php
                                $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product);
                                echo $stock->getQty();
                                ?>">
                            <em class="range"></em>
                        </span>
                    </div>
					<?php if($cart): ?>
						<?php if($_product->isSaleable()): ?>
							<button type="button" title="<?php echo $this->__('Lägg i varukorgen') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Köp') ?></span></span></button>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
					<?php endif; ?>
				</div>
			</div>
			<?php echo $helpLabels->getLabels($_product); //Product labels ?>
		</div>
		</li>
	<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
	</ul>
	<?php endif ?>
	<?php endforeach ?>
    </div>
    <?php $_count++;endforeach;?>

	<?php if ($slide && $rows > 1): ?>
	</div>
    </div>
	<?php endif ?>
	<?php $slide = 0 ;if($slide) : ?>
		<script type="text/javascript">
			jQuery(document).ready(function($){
                (function(selector){
                    var $content = $(selector);
                    var $slider  = $('<?php echo $class ?>', $content);
                    var slider 	 = $slider.bxSlider({
                        <?php echo $this->setBxslider() ?>
                        //infiniteLoop: false,
                        moveSlides:1,
                        //slideMargin: 10,
                        autoHover: true, // stop while hover <=> slider.stopAuto(); + slider.startAuto();
                    })
                })(".featuredproduct");
			});
		</script>
	<?php endif ?>
    <script type="text/javascript">
        //new add by jerry at 2017/09/05 18:13
        jQuery(document).ready(function($){
            $(".featuredproduct .bx-title .feature_title>li").mouseover(function(){
                if(!$(this).hasClass("active")){
                    $(this).addClass("active").siblings().removeClass("active");
                    var tmpIndex = $(this).index();
                    $(".featuredproduct .featuredBox").eq(tmpIndex).addClass("active").siblings().removeClass("active");
                }else {
                    return;
                }
            });
        });
    </script>
</div>
<?php ?>
